version: '2'
services:
  prometheus:
      image: prom/prometheus:latest
      volumes:
          - prometheus_data:/prometheus
      command:
          - '--config.file=/etc/prometheus/prometheus.yml'
      ports:
          - '9090:9090'

  #hystrix_exporter:
  #        image: maurely/hystrix_exporter:latest
  #        ports:
  #            - '9444:9444'

  grafana:
        image: grafana/grafana:latest
        volumes:
            - grafana_data:/var/lib/grafana
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=grafana_secret
        depends_on:
            - prometheus
        ports:
            - "3000:3000"

volumes:
        prometheus_data: {}
        grafana_data: {}
